# Generated by Django 4.2.1 on 2023-05-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
